[env]
  listen_port = 3000

[datasources]
  source = "default"

  [datasources.default]
    dialect = "postgresql"
    host = "localhost"
    port = 5432
    schema = "public"
    database = "funny_project"
    username = ""
    password = ""

    [datasources.default.pool]
      max = 10
      min = 0
      acquire = 30000
      idle = 10000

    [datasources.default.options]
      ssl = false
      connectTimeout = 60000